CREATE IF NOT EXISTS TABLE qr_code (
	id VARCHAR(60) NOT NULL DEFAULT (UUID()),
	email VARCHAR(100) NOT NULL,
	is_active BOOLEAN NOT NULL DEFAULT TRUE,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NULL,
	CONSTRAINT pk_qr_code_uuid PRIMARY KEY (id),
	CONSTRAINT unq_qr_code_email UNIQUE (email)
);